services:

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z-cpuv1 
    container_name: minio
    environment:
      - MINIO_ROOT_USER=User
      - MINIO_ROOT_PASSWORD=p4ssw0rd
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: always
    env_file:
      - local.env
    
    ports:
      - "5432:5432"
    networks:
      - some-network
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/script.sql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    ports:
      - "8080:80"
    networks:
      - some-network
networks:
  some-network:
    driver: bridge