services:

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z-cpuv1
    container_name: minio
    environment:
      - MINIO_ROOT_USER=User
      - MINIO_ROOT_PASSWORD=p4ssw0rd
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - some-network
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: always
    env_file:
      - local.env
    ports:
      - "5432:5432"
    networks:
      - some-network
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/script.sql
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    ports:
      - "8080:80"
    networks:
      - some-network

  backend:
    image: hugostevenpoveda692/fast-app:latest
    container_name: fastapp
    ports: 
      - "8000:8000"
    networks:
      - some-network
  frontend:
    image: hugostevenpoveda692/biblo-radar:latest
    container_name: reactapp
    ports: 
      - "3000:3000"
    networks:
      - some-network

  apivectorial:
    image: hugostevenpoveda692/api-vectorial:lates
    container_name: appvectorial
    ports: 
      - "7000:7000"
    networks:
      - some-network
      
  scripts:
    image: hugostevenpoveda692/app-script:latest
    container_name: scriptapp
    networks:
      - some-network

  scriptsloads:
    image: hugostevenpoveda692/load-script:latest
    container_name: scriptapploads
    networks:
      - some-network
  
  

volumes:
  index_data:
    driver: local
  postgis_data:
    driver: local

networks:
  some-network:
    driver: bridge
